version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: savannah_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/savannah_db
      SECRET_KEY: dev-secret-key
      DEBUG: "true"
      AFRICAS_TALKING_SANDBOX: "true"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: