{{- if .Values.celery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "savannah-microservice.fullname" . }}-celery
  labels:
    {{- include "savannah-microservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  replicas: {{ .Values.celery.replicaCount }}
  selector:
    matchLabels:
      {{- include "savannah-microservice.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        {{- include "savannah-microservice.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "savannah-microservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: celery-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery", "-A", "savannah_microservice", "worker", "--loglevel=info"]
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "savannah-microservice.fullname" . }}-secret
                  key: secret-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "savannah-microservice.fullname" . }}-secret
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "savannah-microservice.fullname" . }}-secret
                  key: redis-url
            - name: AFRICAS_TALKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "savannah-microservice.fullname" . }}-secret
                  key: africastalking-username
            - name: AFRICAS_TALKING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "savannah-microservice.fullname" . }}-secret
                  key: africastalking-api-key
            - name: AFRICAS_TALKING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "savannah-microservice.fullname" . }}-secret
                  key: africastalking-sender-id
            - name: DEBUG
              value: {{ .Values.env.DEBUG | quote }}
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
