apiVersion: v1
kind: Secret
metadata:
  name: {{ include "savannah-microservice.fullname" . }}-secret
  labels:
    {{- include "savannah-microservice.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  africastalking-username: {{ .Values.secrets.africastalkingUsername | b64enc | quote }}
  africastalking-api-key: {{ .Values.secrets.africastalkingApiKey | b64enc | quote }}
  africastalking-sender-id: {{ .Values.secrets.africastalkingSenderId | b64enc | quote }}
